frontend:
  name: frontend
  image:
    repository: ghcr.io/bennyro-mta/todolist
    tag: "1.9"
  service:
    type: LoadBalancer
    port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
      
backend:
  name: mariadb
  image:
    repository: mariadb
    tag: "11"
  service:
    port: 3306

mysql:
  db: todo
backup:
  pvc:
    enabled: true
    name: mariadb-backup-pvc
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: standard

  cronjob:
    enabled: true
    schedule: "0 2 * * *"
    image: mariadb:11

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilization: 50
