frontend:
  name: frontend
  image:
    repository: ghcr.io/bennyro-mta/todolist-vue
    tag: "1.2"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  probes:
    liveness:
      enabled: true
      path: /livez
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 2
      failureThreshold: 3
    readiness:
      enabled: true
      path: /readyz
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3

api:
  name: todo-api
  image:
    repository: ghcr.io/bennyro-mta/todos-api
    tag: "1.2"
  service:
    port: 8080

backend:
  name: mariadb
  image:
    repository: mariadb
    tag: "11"
  service:
    port: 3306
  probes:
    readiness:
      enabled: true
      port: 3306
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

user: "Faber - Shaun"

apiBaseUrl: "http://localhost:8080/todos"

mysql:
  db: todo
  
backup:
  pvc:
    enabled: true
    name: mariadb-backup-pvc
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: standard

  cronjob:
    enabled: true
    schedule: "0 2 * * *"
    image: mariadb:11

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilization: 50

ingress:
  enabled: true
  className: "nginx"
  host: "todolist.local"