apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../3-with-hpa

patches:
  - path: frontend-probes-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: mariadb-probe-patch.yaml
    target:
      kind: StatefulSet
      name: mariadb