apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist-chart.fullname" . }}-config
data:
  MYSQL_DB: "{{ .Values.mysql.db }}"
  MYSQL_HOST: "{{ include "todolist-chart.backendName" . }}-0.{{ include "todolist-chart.backendHeadlessName" . }}"

