apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist-chart.fullname" . }}-config
data:
  USER: {{ .Values.user | quote }}
  MYSQL_DB: "{{ .Values.mysql.db }}"
  MYSQL_HOST: "{{ include "todolist-chart.backendName" . }}-0.{{ include "todolist-chart.backendHeadlessName" . }}"
binaryData:
  title-image.png: {{ .Files.Get "files/title-image.png" | b64enc }}
