apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist-chart.frontendName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "todolist-chart.frontendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "todolist-chart.frontendName" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist-chart.fullname" . }}-config
                  key: MYSQL_HOST

            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist-chart.fullname" . }}-config
                  key: MYSQL_DB

            - name: MYSQL_USER
              value: root
              
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysql.name }}
                  key: MYSQL_ROOT_PASSWORD
