{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todolist-chart.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "todolist-chart.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "todolist-chart.frontendName" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}